spring:
  application:
    name: restaurant-ordering-system
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_ordering_system
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  liquibase:
    change-log: classpath:/liquibase/master.xml
server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

