spring:
  application:
    name: restaurant-ordering-system
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_ordering_system
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  liquibase:
    change-log: classpath:/liquibase/master.xml
  mail:
    host: smtp.gmail.com
    port: 25
    username: ${email}
    password: ${password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka